use serde::Serialize;

/// Primitive setting type used to generate UI fields and command suggestions.
#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum SettingValueType {
    String,
    Integer,
    Boolean,
    Hotkey,
    Secret,
}

/// Schema metadata for one flat configuration key.
#[derive(Debug, Clone, Serialize)]
pub struct SettingSchema {
    pub key: &'static str,
    pub section: &'static str,
    pub label: &'static str,
    pub value_type: SettingValueType,
    pub default_value: &'static str,
    pub sensitive: bool,
    pub options: &'static [&'static str],
}

impl SettingSchema {
    pub const fn new(
        key: &'static str,
        section: &'static str,
        label: &'static str,
        value_type: SettingValueType,
        default_value: &'static str,
        sensitive: bool,
        options: &'static [&'static str],
    ) -> Self {
        Self {
            key,
            section,
            label,
            value_type,
            default_value,
            sensitive,
            options,
        }
    }
}

/// Returns the built-in setting schema in stable display order.
pub fn builtin_setting_schema() -> Vec<SettingSchema> {
    use SettingValueType::{Boolean, Hotkey, Integer, Secret, String};

    vec![
        SettingSchema::new(
            "hotkeys.app_launcher",
            "hotkeys",
            "App launcher",
            Hotkey,
            "Ctrl+K",
            false,
            &[],
        ),
        SettingSchema::new(
            "hotkeys.mouse_control",
            "hotkeys",
            "Mouse control",
            Hotkey,
            "Ctrl+Alt+M",
            false,
            &[],
        ),
        SettingSchema::new(
            "hotkeys.workspace_1",
            "hotkeys",
            "Workspace 1",
            Hotkey,
            "Ctrl+Alt+1",
            false,
            &[],
        ),
        SettingSchema::new(
            "hotkeys.workspace_2",
            "hotkeys",
            "Workspace 2",
            Hotkey,
            "Ctrl+Alt+2",
            false,
            &[],
        ),
        SettingSchema::new(
            "hotkeys.workspace_3",
            "hotkeys",
            "Workspace 3",
            Hotkey,
            "Ctrl+Alt+3",
            false,
            &[],
        ),
        SettingSchema::new(
            "launcher.max_results",
            "launcher",
            "Max results",
            Integer,
            "10",
            false,
            &[],
        ),
        SettingSchema::new(
            "launcher.cache_ttl_secs",
            "launcher",
            "Cache TTL",
            Integer,
            "300",
            false,
            &[],
        ),
        SettingSchema::new(
            "search.backend",
            "search",
            "Search backend",
            String,
            "auto",
            false,
            &["auto", "everything", "app_cache", "tantivy"],
        ),
        SettingSchema::new(
            "search.index_dir",
            "search",
            "Search index directory",
            String,
            "",
            false,
            &[],
        ),
        SettingSchema::new(
            "search.exclude_dirs",
            "search",
            "Search excluded directories",
            String,
            "AppData,node_modules,.git,target,dist",
            false,
            &[],
        ),
        SettingSchema::new(
            "search.max_file_results",
            "search",
            "Max file results",
            Integer,
            "50",
            false,
            &[],
        ),
        SettingSchema::new(
            "terminal.default_shell",
            "terminal",
            "Default shell",
            String,
            "",
            false,
            &[],
        ),
        SettingSchema::new(
            "terminal.font_size",
            "terminal",
            "Font size",
            Integer,
            "14",
            false,
            &[],
        ),
        SettingSchema::new(
            "terminal.scrollback_lines",
            "terminal",
            "Scrollback lines",
            Integer,
            "1000",
            false,
            &[],
        ),
        SettingSchema::new(
            "mouse_control.step_size",
            "mouse_control",
            "Step size",
            Integer,
            "10",
            false,
            &[],
        ),
        SettingSchema::new(
            "mouse_control.fast_step_size",
            "mouse_control",
            "Fast step size",
            Integer,
            "50",
            false,
            &[],
        ),
        SettingSchema::new(
            "features.ai",
            "features",
            "AI Chat & Assistant",
            Boolean,
            "false",
            false,
            &["true", "false"],
        ),
        SettingSchema::new(
            "features.agent",
            "features",
            "AI Agent (ReAct)",
            Boolean,
            "false",
            false,
            &["true", "false"],
        ),
        SettingSchema::new(
            "features.translation",
            "features",
            "Translation",
            Boolean,
            "true",
            false,
            &["true", "false"],
        ),
        SettingSchema::new(
            "features.notes",
            "features",
            "Notes",
            Boolean,
            "true",
            false,
            &["true", "false"],
        ),
        SettingSchema::new(
            "features.history",
            "features",
            "History",
            Boolean,
            "true",
            false,
            &["true", "false"],
        ),
        SettingSchema::new(
            "features.calculator",
            "features",
            "Calculator",
            Boolean,
            "true",
            false,
            &["true", "false"],
        ),
        SettingSchema::new(
            "features.system",
            "features",
            "System",
            Boolean,
            "true",
            false,
            &["true", "false"],
        ),
        SettingSchema::new(
            "ai.provider",
            "ai",
            "Provider",
            String,
            "claude",
            false,
            &["claude", "ollama", "openai"],
        ),
        SettingSchema::new("ai.api_key", "ai", "Claude API key", Secret, "", true, &[]),
        SettingSchema::new(
            "ai.model",
            "ai",
            "Claude model",
            String,
            "claude-sonnet-4-6",
            false,
            &[],
        ),
        SettingSchema::new(
            "ai.claude_model",
            "ai",
            "Claude model alias",
            String,
            "claude-sonnet-4-6",
            false,
            &[],
        ),
        SettingSchema::new(
            "ai.ollama_url",
            "ai",
            "Ollama URL",
            String,
            "http://localhost:11434",
            false,
            &[],
        ),
        SettingSchema::new(
            "ai.ollama_timeout_secs",
            "ai",
            "Ollama timeout",
            Integer,
            "120",
            false,
            &[],
        ),
        SettingSchema::new(
            "ai.openai_api_key",
            "ai",
            "OpenAI-compatible API key",
            Secret,
            "",
            true,
            &[],
        ),
        SettingSchema::new(
            "ai.openai_base_url",
            "ai",
            "OpenAI-compatible base URL",
            String,
            "https://api.openai.com/v1",
            false,
            &[],
        ),
        SettingSchema::new(
            "ai.openai_model",
            "ai",
            "OpenAI-compatible model",
            String,
            "gpt-4o-mini",
            false,
            &[],
        ),
        SettingSchema::new(
            "ai.max_tokens",
            "ai",
            "Max tokens",
            Integer,
            "4096",
            false,
            &[],
        ),
        SettingSchema::new(
            "ai.timeout_secs",
            "ai",
            "AI timeout",
            Integer,
            "30",
            false,
            &[],
        ),
        SettingSchema::new(
            "agent.web_search_provider",
            "agent",
            "Web search provider",
            String,
            "disabled",
            false,
            &["disabled", "searxng", "tavily", "duckduckgo"],
        ),
        SettingSchema::new(
            "agent.long_term_memory_opt_in",
            "agent",
            "Long-term memory opt-in",
            Boolean,
            "false",
            false,
            &["true", "false"],
        ),
        SettingSchema::new(
            "agent.searxng_url",
            "agent",
            "SearXNG URL",
            String,
            "",
            false,
            &[],
        ),
        SettingSchema::new(
            "agent.web_search_api_key",
            "agent",
            "Web search API key",
            Secret,
            "",
            true,
            &[],
        ),
        SettingSchema::new(
            "agent.web_search_timeout_secs",
            "agent",
            "Web search timeout",
            Integer,
            "8",
            false,
            &[],
        ),
        SettingSchema::new(
            "translation.default_src",
            "translation",
            "Default source",
            String,
            "auto",
            false,
            &[],
        ),
        SettingSchema::new(
            "translation.default_dst",
            "translation",
            "Default target",
            String,
            "zh-TW",
            false,
            &[],
        ),
        SettingSchema::new(
            "translation.provider",
            "translation",
            "Provider",
            String,
            "google_free",
            false,
            &["google_free"],
        ),
        SettingSchema::new(
            "translation.timeout_secs",
            "translation",
            "Translation timeout",
            Integer,
            "30",
            false,
            &[],
        ),
        SettingSchema::new(
            "notes.storage_dir",
            "notes",
            "Storage directory",
            String,
            "",
            false,
            &[],
        ),
        SettingSchema::new(
            "notes.default_extension",
            "notes",
            "Default extension",
            String,
            "md",
            false,
            &[],
        ),
        SettingSchema::new(
            "notes.lazyvim_command",
            "notes",
            "LazyVim command",
            String,
            "",
            false,
            &[],
        ),
        SettingSchema::new(
            "notes.lazyvim_config_dir",
            "notes",
            "LazyVim config directory",
            String,
            "",
            false,
            &[],
        ),
        SettingSchema::new(
            "history.max_items",
            "history",
            "Max items",
            Integer,
            "200",
            false,
            &[],
        ),
        SettingSchema::new(
            "history.ignore_duplicates",
            "history",
            "Ignore duplicates",
            Boolean,
            "true",
            false,
            &["true", "false"],
        ),
        SettingSchema::new(
            "system.enable_volume_control",
            "system",
            "Volume control",
            Boolean,
            "true",
            false,
            &["true", "false"],
        ),
        SettingSchema::new(
            "system.enable_brightness_control",
            "system",
            "Brightness control",
            Boolean,
            "true",
            false,
            &["true", "false"],
        ),
        SettingSchema::new(
            "system.enable_wifi_info",
            "system",
            "Wi-Fi info",
            Boolean,
            "true",
            false,
            &["true", "false"],
        ),
        SettingSchema::new(
            "performance.low_memory_mode",
            "performance",
            "Low memory mode",
            Boolean,
            "false",
            false,
            &["true", "false"],
        ),
        SettingSchema::new(
            "ai.ollama_keep_alive",
            "ai",
            "Ollama keep-alive",
            String,
            "5m",
            false,
            &[],
        ),
        SettingSchema::new(
            "security.network_allowlist",
            "security",
            "Outbound network allowlist",
            String,
            "api.anthropic.com,api.openai.com,translate.googleapis.com,api.tavily.com,duckduckgo.com,github.com",
            false,
            &[],
        ),
        SettingSchema::new(
            "agent.local_context.enabled",
            "agent",
            "Local context review (enabled)",
            Boolean,
            "false",
            false,
            &["true", "false"],
        ),
        SettingSchema::new(
            "agent.local_context.max_scan_files",
            "agent",
            "Local context max scan files",
            Integer,
            "500",
            false,
            &[],
        ),
        SettingSchema::new(
            "agent.local_context.max_preview_bytes",
            "agent",
            "Local context max preview bytes",
            Integer,
            "4096",
            false,
            &[],
        ),
        SettingSchema::new(
            "agent.local_context.max_depth",
            "agent",
            "Local context scan depth",
            Integer,
            "4",
            false,
            &[],
        ),
        SettingSchema::new(
            "agent.local_context.extra_denylist",
            "agent",
            "Local context extra denylist (comma-separated)",
            String,
            "",
            false,
            &[],
        ),
    ]
}

pub fn is_sensitive_key(key: &str) -> bool {
    builtin_setting_schema()
        .iter()
        .any(|schema| schema.key == key && schema.sensitive)
}

pub fn redact_setting_value(key: &str, value: &str) -> String {
    if is_sensitive_key(key) && !value.is_empty() {
        String::new()
    } else {
        value.to_string()
    }
}
