#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";

const ROOT = process.cwd();
const STAGED_ONLY = process.argv.includes("--staged");

const KEY_STATE_DOCS = new Set([
  "docs/tasks/active.md",
  "docs/tasks/backlog.md",
  "docs/tasks/blocked.md",
  "docs/tasks/completed.md",
  "docs/memory/current.md",
]);

const REQUIRED_FRONTMATTER = [
  "CLAUDE.md",
  "docs/CLAUDE.md",
  "docs/project.md",
  "docs/index.md",
  "docs/tasks.md",
  "docs/tasks/active.md",
  "docs/tasks/backlog.md",
  "docs/tasks/blocked.md",
  "docs/tasks/completed.md",
  "docs/memory.md",
  "docs/memory/current.md",
  "docs/architecture.md",
  "docs/security.md",
  "docs/testing.md",
  "docs/decisions.md",
];

function normalize(input) {
  return input.replace(/\\/g, "/");
}

function run(command) {
  try {
    return execSync(command, {
      cwd: ROOT,
      stdio: ["ignore", "pipe", "ignore"],
      encoding: "utf8",
    });
  } catch {
    return "";
  }
}

function getChangedFiles() {
  const changed = new Set();
  const commands = STAGED_ONLY
    ? ["git diff --cached --name-only"]
    : ["git diff --name-only", "git diff --cached --name-only"];
  for (const command of commands) {
    run(command)
      .split(/\r?\n/)
      .map((line) => normalize(line.trim()))
      .filter(Boolean)
      .forEach((line) => changed.add(line));
  }
  return changed;
}

function hasRequiredFrontmatter(filePath) {
  if (!fs.existsSync(filePath)) {
    return false;
  }
  const content = fs.readFileSync(filePath, "utf8").replace(/^\uFEFF/, "").replace(/\r\n/g, "\n");
  const match = content.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!match) {
    return false;
  }
  const block = match[1];
  const required = ["type:", "status:", "updated:", "context_policy:"];
  return required.every((field) => block.includes(field));
}

const changed = getChangedFiles();
const codeChanged = [...changed].some(
  (file) => file.startsWith("src/") || file.startsWith("src-tauri/"),
);
const stateDocsChanged = [...changed].some((file) => KEY_STATE_DOCS.has(file));

if (codeChanged && !stateDocsChanged) {
  console.error(
    "[docs-guard] Code changed under src/ or src-tauri/, but no project-state docs were updated.",
  );
  console.error(
    "[docs-guard] Update at least one of: docs/tasks/{active,backlog,blocked,completed}.md or docs/memory/current.md",
  );
  process.exit(1);
}

const missingFrontmatter = REQUIRED_FRONTMATTER.filter(
  (file) => !hasRequiredFrontmatter(path.join(ROOT, file)),
);
if (missingFrontmatter.length > 0) {
  console.error("[docs-guard] Missing required frontmatter fields in:");
  for (const file of missingFrontmatter) {
    console.error(`  - ${file}`);
  }
  process.exit(1);
}

const indexPath = path.join(ROOT, "docs", "index.md");
if (!fs.existsSync(indexPath)) {
  console.error("[docs-guard] docs/index.md is missing.");
  process.exit(1);
}

const indexContent = fs.readFileSync(indexPath, "utf8");
if (!indexContent.includes("AUTO-GENERATED by scripts/docs-sync.mjs")) {
  console.error("[docs-guard] docs/index.md is not synchronized. Run npm run docs:sync.");
  process.exit(1);
}

console.log("[docs-guard] Documentation guard checks passed.");
